image: node:lts

pages:
  cache:
    paths:
      - node_modules/
    key:
      files:
        - pnpm-lock.yaml
  before_script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - corepack enable
    - corepack prepare pnpm@latest --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
  artifacts:
    paths:
      - public
  only:
    - main